/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDuplicateMembersRouteImport } from './routes/_authenticated/duplicate-members'
import { Route as AuthenticatedHouseholdsRouteImport } from './routes/_authenticated/households'
import { Route as AuthenticatedMemberListRouteImport } from './routes/_authenticated/member-list'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedMyDashboardRouteImport } from './routes/_authenticated/my-dashboard'
import { Route as AuthenticatedPurokLeadersRouteImport } from './routes/_authenticated/purok-leaders'
import { Route as AuthenticatedPuroksRouteImport } from './routes/_authenticated/puroks'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDuplicateMembersRoute =
  AuthenticatedDuplicateMembersRouteImport.update({
    id: '/duplicate-members',
    path: '/duplicate-members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHouseholdsRoute = AuthenticatedHouseholdsRouteImport.update({
  id: '/households',
  path: '/households',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMemberListRoute = AuthenticatedMemberListRouteImport.update({
  id: '/member-list',
  path: '/member-list',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyDashboardRoute =
  AuthenticatedMyDashboardRouteImport.update({
    id: '/my-dashboard',
    path: '/my-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurokLeadersRoute =
  AuthenticatedPurokLeadersRouteImport.update({
    id: '/purok-leaders',
    path: '/purok-leaders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPuroksRoute = AuthenticatedPuroksRouteImport.update({
  id: '/puroks',
  path: '/puroks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/duplicate-members': typeof AuthenticatedDuplicateMembersRoute
  '/households': typeof AuthenticatedHouseholdsRoute
  '/member-list': typeof AuthenticatedMemberListRoute
  '/members': typeof AuthenticatedMembersRoute
  '/my-dashboard': typeof AuthenticatedMyDashboardRoute
  '/purok-leaders': typeof AuthenticatedPurokLeadersRoute
  '/puroks': typeof AuthenticatedPuroksRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/duplicate-members': typeof AuthenticatedDuplicateMembersRoute
  '/households': typeof AuthenticatedHouseholdsRoute
  '/member-list': typeof AuthenticatedMemberListRoute
  '/members': typeof AuthenticatedMembersRoute
  '/my-dashboard': typeof AuthenticatedMyDashboardRoute
  '/purok-leaders': typeof AuthenticatedPurokLeadersRoute
  '/puroks': typeof AuthenticatedPuroksRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/duplicate-members': typeof AuthenticatedDuplicateMembersRoute
  '/_authenticated/households': typeof AuthenticatedHouseholdsRoute
  '/_authenticated/member-list': typeof AuthenticatedMemberListRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/my-dashboard': typeof AuthenticatedMyDashboardRoute
  '/_authenticated/purok-leaders': typeof AuthenticatedPurokLeadersRoute
  '/_authenticated/puroks': typeof AuthenticatedPuroksRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/duplicate-members'
    | '/households'
    | '/member-list'
    | '/members'
    | '/my-dashboard'
    | '/purok-leaders'
    | '/puroks'
    | '/reports'
    | '/security'
    | '/settings'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/duplicate-members'
    | '/households'
    | '/member-list'
    | '/members'
    | '/my-dashboard'
    | '/purok-leaders'
    | '/puroks'
    | '/reports'
    | '/security'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/duplicate-members'
    | '/_authenticated/households'
    | '/_authenticated/member-list'
    | '/_authenticated/members'
    | '/_authenticated/my-dashboard'
    | '/_authenticated/purok-leaders'
    | '/_authenticated/puroks'
    | '/_authenticated/reports'
    | '/_authenticated/security'
    | '/_authenticated/settings'
    | '/_authenticated/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/duplicate-members': {
      id: '/_authenticated/duplicate-members'
      path: '/duplicate-members'
      fullPath: '/duplicate-members'
      preLoaderRoute: typeof AuthenticatedDuplicateMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/households': {
      id: '/_authenticated/households'
      path: '/households'
      fullPath: '/households'
      preLoaderRoute: typeof AuthenticatedHouseholdsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/member-list': {
      id: '/_authenticated/member-list'
      path: '/member-list'
      fullPath: '/member-list'
      preLoaderRoute: typeof AuthenticatedMemberListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-dashboard': {
      id: '/_authenticated/my-dashboard'
      path: '/my-dashboard'
      fullPath: '/my-dashboard'
      preLoaderRoute: typeof AuthenticatedMyDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purok-leaders': {
      id: '/_authenticated/purok-leaders'
      path: '/purok-leaders'
      fullPath: '/purok-leaders'
      preLoaderRoute: typeof AuthenticatedPurokLeadersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/puroks': {
      id: '/_authenticated/puroks'
      path: '/puroks'
      fullPath: '/puroks'
      preLoaderRoute: typeof AuthenticatedPuroksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDuplicateMembersRoute: typeof AuthenticatedDuplicateMembersRoute
  AuthenticatedHouseholdsRoute: typeof AuthenticatedHouseholdsRoute
  AuthenticatedMemberListRoute: typeof AuthenticatedMemberListRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedMyDashboardRoute: typeof AuthenticatedMyDashboardRoute
  AuthenticatedPurokLeadersRoute: typeof AuthenticatedPurokLeadersRoute
  AuthenticatedPuroksRoute: typeof AuthenticatedPuroksRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDuplicateMembersRoute: AuthenticatedDuplicateMembersRoute,
  AuthenticatedHouseholdsRoute: AuthenticatedHouseholdsRoute,
  AuthenticatedMemberListRoute: AuthenticatedMemberListRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedMyDashboardRoute: AuthenticatedMyDashboardRoute,
  AuthenticatedPurokLeadersRoute: AuthenticatedPurokLeadersRoute,
  AuthenticatedPuroksRoute: AuthenticatedPuroksRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
